### ISSUE TITLE
Pipeline optimization and AXI4

### ISSUE THREAD

**Issue by armleo** [armleo/ArmleoCPU#3]
Instead of keeping 2 stages have multiple stage:
Prefetch, fetch, decode, execute, mem, writeback.

Replace I/D-bus with AXI4 so that it can be simply pipelined.

**Comment by ZipCPU** [comment]
I don't get this one.  Why is pipelining on an AXI4 bus a waste of cycles?

**Comment by armleo** [comment]
I wanted AXI4 so I could replace I/D-Cache with no Cache at all, but then it would mean I had to implement a 3 cycle pipeline per instruction fetch because of TLB and virtual memory, and in the case of the branch they had to just be thrown away.

I also rejected the idea because it was a waste of time, because of the high latency of the chip2chip connection that I was gonna implement for skywater130 tapeout I just decided to not do it entirely.
